ALTER TABLE "future_expense_payables" DROP CONSTRAINT "future_expense_payables_category_valid";--> statement-breakpoint
ALTER TABLE "monthly_expense_entries" DROP CONSTRAINT "monthly_expense_entries_category_valid";--> statement-breakpoint
ALTER TABLE "monthly_expense_entries" DROP CONSTRAINT "monthly_expense_entries_requires_fields_when_unlinked";--> statement-breakpoint
ALTER TABLE "monthly_expenses" DROP CONSTRAINT "monthly_expenses_category_valid";--> statement-breakpoint
ALTER TABLE "future_expense_payables" ADD COLUMN "occurrence_type" text DEFAULT 'planned_one_off' NOT NULL;--> statement-breakpoint
ALTER TABLE "monthly_expense_entries" ADD COLUMN "occurrence_type" text;--> statement-breakpoint
UPDATE "monthly_expense_entries" SET "occurrence_type" = 'unexpected' WHERE "monthly_expense_id" IS NULL AND "occurrence_type" IS NULL;--> statement-breakpoint
ALTER TABLE "future_expense_payables" ADD CONSTRAINT "future_expense_payables_occurrence_type_valid" CHECK ("future_expense_payables"."occurrence_type" IN ('planned_one_off','unexpected'));--> statement-breakpoint
ALTER TABLE "future_expense_payables" ADD CONSTRAINT "future_expense_payables_category_valid" CHECK ("future_expense_payables"."category" IN ('moradia','dividas','transporte','alimentacao','esportes','beleza_cuidados','reserva','doacoes','lazer','educacao','saude','compras','servicos','assinaturas','familia','impostos','outros'));--> statement-breakpoint
ALTER TABLE "monthly_expense_entries" ADD CONSTRAINT "monthly_expense_entries_occurrence_type_valid" CHECK ("monthly_expense_entries"."occurrence_type" IS NULL OR "monthly_expense_entries"."occurrence_type" IN ('planned_one_off','unexpected'));--> statement-breakpoint
ALTER TABLE "monthly_expense_entries" ADD CONSTRAINT "monthly_expense_entries_category_valid" CHECK ("monthly_expense_entries"."category" IS NULL OR "monthly_expense_entries"."category" IN ('moradia','dividas','transporte','alimentacao','esportes','beleza_cuidados','reserva','doacoes','lazer','educacao','saude','compras','servicos','assinaturas','familia','impostos','outros'));--> statement-breakpoint
ALTER TABLE "monthly_expense_entries" ADD CONSTRAINT "monthly_expense_entries_requires_fields_when_unlinked" CHECK ("monthly_expense_entries"."monthly_expense_id" IS NOT NULL OR ("monthly_expense_entries"."name" IS NOT NULL AND "monthly_expense_entries"."category" IS NOT NULL AND "monthly_expense_entries"."expense_type" IS NOT NULL AND "monthly_expense_entries"."occurrence_type" IS NOT NULL));--> statement-breakpoint
ALTER TABLE "monthly_expenses" ADD CONSTRAINT "monthly_expenses_category_valid" CHECK ("monthly_expenses"."category" IN ('moradia','dividas','transporte','alimentacao','esportes','beleza_cuidados','reserva','doacoes','lazer','educacao','saude','compras','servicos','assinaturas','familia','impostos','outros'));
